version: '3.8'
services:
    database:
        image: postgres
        env_file:
            - .env
        volumes:
            - postgres-db:/var/lib/postgresql/data
    api:
        build: ./backend
        ports:
            - 8000:8000
        env_file:
            - .env
    client:
        build:
            context: ./frontend
            args:
                - VITE_GOOGLE_CLIENT_ID=${VITE_GOOGLE_CLIENT_ID}
                - VITE_API_DOMAIN=${VITE_API_DOMAIN}
        ports:
            - 8080:8080
        env_file:
            - .env

volumes:
    postgres-db:
